str='''The wise traveller travels only in imagination. An old Frenchman (he was really a Savoyard) once wrote a book called Voyage autour de ma Chambre. I have not read it and do not even know what it is about, but the title stimulates my fancy. In such a journey I could circumnavigate the globe. An eikon by the chimneypiece can take me to Russia with its great forests of birch and its white, domed churches. The Volga is wide, and at the end of a straggling village, in the wine-shop, bearded men in rough sheepskin coats sit drinking. I stand on the little hill from which Napoleon first saw Moscow and I look upon the vastness of the city. I will go down and see the people whom I know more intimately than so many of my friends, Alyosha, and Vronsky, and a dozen more. But my eyes fall on a piece of porcelain and I smell the acrid odours of China. I am borne in a chair along a narrow causeway between the padi fields, or else I skirt a tree-clad mountain. My bearers chat gaily as they trudge along in the bright morning and every now and then, distant and mysterious, I hear the deep sound of a monastery bell. In the streets of Peking there is a motley crowd and it scatters to allow passage to a string of camels, stepping delicately, that bring skins and strange drugs from the stony deserts of Mongolia. In England, in London, there are certain afternoons in winter when the clouds hang heavy and low and the light is so bleak that your heart sinks, but then you can look out of your window, and you see the coconut trees crowded upon the beach of a coral island. The strand is silvery and when you walk along in the sunshine it is so dazzling that you can hardly bear to look at it. Overhead the mynah birds are making a great to-do, and the surf beats ceaselessly against the reef. Those are the best journeys, the journeys that you take at your own fireside, for then you lose none of your illusions.

But there are people who take salt in their coffee. They say it gives it a tang, a savour, which is peculiar and fascinating. In the same way there are certain places, surrounded by a halo of romance, to which the inevitable disillusionment which you must experience on seeing them gives a singular spice. You had expected something wholly beautiful and you get an impression which is infinitely more complicated than any that beauty can give you. It is like the weakness in the character of a great man which may make him less admirable but certainly makes him more interesting.'''
#how chunking looks like
def chunker(str, chunk_size =100):
  formated_string=''.join(str.split('\n'))
  words = formated_string.split()
  chunks=[' '.join(words[0:1+chunk_size]) for i in range(0,len(words),chunk_size)]
  print(chunks)

chunker(str)
